FROM node:latest

# Go to the working directory
RUN mkdir -p /usr/src/app/
WORKDIR /usr/src/app/

# Copy package.json over
COPY package*.json ./

# Install
RUN npm config set strict-ssl false
RUN npm install

# Copy over
COPY . .

# Export the port
EXPOSE 3000

CMD npm run start -FAST_REFRESH=true