FROM node:12.19-alpine

# Go to the working directory
WORKDIR /

# Copy over
COPY . .

# Install
RUN npm config set strict-ssl false
RUN npm install

# Export the port
EXPOSE 3000

# Start
CMD npm run start