version: '3.3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    depends_on:
      - frontend
      - backend
    links:
      - frontend
      - backend
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/server.log:/etc/nginx/logs/server.log
    networks:
      - host-bridged
  frontend:
    build: ./frontend/
    container_name: frontend
    networks:
      - host-bridged
    volumes:
      - ./frontend/:/usr/src/app/
  backend:
    build: ./backend/
    container_name: backend
    networks:
      - host-bridged
    volumes:
      - ./backend/:/usr/src/app/
  redis:
    depends_on:
      - frontend
    networks:
      - host-bridged

networks:
  container-only:
    driver: bridge
    internal: true
  host-bridged:
    driver: bridge
