version: '3.3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    depends_on:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443
    links:
      - frontend
      - backend
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/server.log:/etc/nginx/logs/server.log
    networks:
      - host-bridged

  frontend:
    build:
      context: ./react-app/
      dockerfile: dockerfile
    container_name: frontend
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    volumes:
      - ./react-app/:/usr/src/app/
      - /usr/src/app/node_modules/
    networks:
      - host-bridged

  backend:
    build:
      context: ./web-api/
      dockerfile: dockerfile
    container_name: backend
    ports:
      - 5000:5000
    volumes:
      - ./web-api/:/usr/src/app/
      - /usr/src/app/node_modules/
    networks:
      - host-bridged

  redis:
    depends_on:
      - frontend
    networks:
      - host-bridged

networks:
  container-only:
    driver: bridge
    internal: true

  host-bridged:
    driver: bridge
